name: gb_crop_assignment_task_app
description: "A beautiful Flutter task management app with Riverpod, Dio, and Clean Architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.2.7

  # Networking
  dio: ^5.4.3+1

  # Secure storage
  flutter_secure_storage: ^9.2.2

  # UI
  google_fonts: ^6.2.1
  shimmer: ^3.0.0

  # Utilities
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
